[package]
name = "aoc2025"
version = "0.1.0"
edition = "2021"
authors = ["johan"]
license = "MIT"
description = "Advent of Code 2025 solutions in Rust"


[profile.release]
# Optimize for runtime performance.
opt-level = 3

[profile.dev]
# Optimize for compilation speed.
opt-level = 1

